# Generated by Django 2.0.5 on 2018-06-29 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('number_of_months', models.IntegerField()),
                ('people_present', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lifted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifted', models.BooleanField(default=False)),
                ('lift_request', models.IntegerField(default=0)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chit', to='chit_app.Chit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
